const houses = [
  {
    id: "0",
    renda: true,
    quartos: 2,
    preco: 2500,
    local: 1,
    andar: 1,
    user: "x",
    user_tel: "872081977",
    disponivel: true,
    photos: [],
  },
  {
    id: "1",
    renda: false,
    quartos: 3,
    preco: 1300000,
    local: 0,
    andar: 2,
    user: "y",
    user_tel: "872081971",
    disponivel: true,
    photos: [],
  },
  {
    id: "2",
    renda: true,
    quartos: 1,
    preco: 1700,
    local: 3,
    andar: 0,
    user: "y",
    user_tel: "872081976",
    disponivel: true,
    photos: [],
  },
  {
    id: "3",
    renda: true,
    quartos: 3,
    preco: 3500,
    local: 1,
    andar: 1,
    user: "y",
    user_tel: "872081976",
    disponivel: true,
    photos: [],
  },
  {
    id: "4",
    renda: true,
    quartos: 2,
    preco: 3500,
    local: 5,
    andar: 2,
    user: "y",
    user_tel: "872081976",
    disponivel: true,
    photos: [],
  },
  {
    id: "5",
    renda: true,
    quartos: 1,
    preco: 1700,
    local: 3,
    andar: 0,
    user: "y",
    user_tel: "872081976",
    disponivel: true,
    photos: [],
  },
  {
    id: "6",
    renda: true,
    quartos: 3,
    preco: 3500,
    local: 1,
    andar: 1,
    user: "y",
    user_tel: "872081976",
    disponivel: true,
    photos: [],
  },
  {
    id: "7",
    renda: true,
    quartos: 3,
    preco: 120000,
    local: 1,
    andar: 1,
    user: "y",
    user_tel: "872081976",
    disponivel: true,
    photos: [],
  },
];
